version: '2'

services:
  base-workspace:
    build:
      context: ./centos-base-workspace-lite
    ports:
      - "${WORKSPACE_PORT}:8500"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_VERSION=${CONSUL_VERSION}
      - CONSULUI_VERSION=${CONSULUI_VERSION}
      - CONSULTEMPLATE_VERSION=${CONSULTEMPLATE_VERSION}
      - RUBY_VERSION=${RUBY_VERSION}
      - CONSUL_OPTIONS=${CONSUL_OPTIONS}              # minimal server options

  application:
    build:
      context: ./centos-application-lite
    depends_on:
      - base-workspace
    ports:
      - "${APPLICATION_PORT}:22"
    volumes_from:
      - base-workspace
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPLICATION}:/application
    environment:
      - SSH_AUTHORIZED_KEYS=${SSH_AUTHORIZED_KEYS}
      - SSH_USER=${SSH_USER}
      - SSH_USER_PASSWORD=${SSH_USER_PASSWORD}
      - SSH_USER_PASSWORD_HASHED=${SSH_USER_PASSWORD_HASHED}
      - CONSUL_SERVICENAME=openssh                    # consul service name
      - CONSUL_SERVICETAGS=dev                        # consul service tag
      - CONSUL_SERVICEPORT=2222                       # consul service port
      - CONSUL_CHECKTYPE=tcp                          # consul health check type
    tty: true
    networks:
      - frontend
      - backend

  postgres:
    build: ./postgres
    links:
      - application
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend


### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  application:
    driver: "local"
  postgres:
    driver: "local"
